config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'search', to:'home#search'
  get 'home/index'
  resources :experiences
  resources :profiles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/experience.rb
class Experience < ApplicationRecord
  validates :name, presence: true
  validates :date_start, presence: true
  validates :date_final, presence: true
  validates :description, presence: true

  belongs_to :profile
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true

  has_many :experiences, inverse_of: :profile, dependent: :delete_all
  accepts_nested_attributes_for :experiences, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: %i[ show edit update destroy ]

  # GET /experiences or /experiences.json
  def index
    @experiences = Experience.all
  end

  # GET /experiences/1 or /experiences/1.json
  def show
  end

  # GET /experiences/new
  def new
    @experience = Experience.new
  end

  # GET /experiences/1/edit
  def edit
  end

  # POST /experiences or /experiences.json
  def create
    @experience = Experience.new(experience_params)

    respond_to do |format|
      if @experience.save
        format.html { redirect_to experience_url(@experience), notice: "Experience was successfully created." }
        format.json { render :show, status: :created, location: @experience }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiences/1 or /experiences/1.json
  def update
    respond_to do |format|
      if @experience.update(experience_params)
        format.html { redirect_to experience_url(@experience), notice: "Experience was successfully updated." }
        format.json { render :show, status: :ok, location: @experience }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiences/1 or /experiences/1.json
  def destroy
    @experience.destroy

    respond_to do |format|
      format.html { redirect_to experiences_url, notice: "Experience was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experience
      @experience = Experience.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def experience_params
      params.require(:experience).permit(:name, :date_start, :date_final, :description, :profile_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @profiles = Profile.all
  end

  def search
    @profiles = Profile.where('name like ? OR email like ? OR phone like ?',
    "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%")
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
    @experiences = @profile.experiences.build
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:name, :email, :url, :phone, experiences_attributes: [ :profile_id, :name, :date_start, :date_final, :description, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper

  def post_date(date)
    # formatting date: Aug, 31 2007 - 9:55PM
    date.strftime("%d / %m / %Y")
  end

end

app/views/experiences/_experience.html.erb
<div id="<%= dom_id experience %>">
  <p>
    <strong>Name:</strong>
    <%= experience.name %>
  </p>

  <p>
    <strong>Date start:</strong>
    <%= experience.date_start %>
  </p>

  <p>
    <strong>Date final:</strong>
    <%= experience.date_final %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= experience.description %>
  </p>

  <p>
    <strong>Profile:</strong>
    <%= experience.profile_id %>
  </p>

</div>

app/views/experiences/_form.html.erb
<%= form_with(model: experience) do |form| %>
  <% if experience.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
        <% experience.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :date_start, style: "display: block" %>
    <%= form.date_field :date_start %>
  </div>

  <div>
    <%= form.label :date_final, style: "display: block" %>
    <%= form.date_field :date_final %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :profile_id, style: "display: block" %>
    <%= form.text_field :profile_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/experiences/edit.html.erb
<h1>Editing experience</h1>

<%= render "form", experience: @experience %>

<br>

<div>
  <%= link_to "Show this experience", @experience %> |
  <%= link_to "Back to experiences", experiences_path %>
</div>

app/views/experiences/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Experiences</h1>

<div id="experiences">
  <% @experiences.each do |experience| %>
    <%= render experience %>
    <p>
      <%= link_to "Show this experience", experience %>
    </p>
  <% end %>
</div>

<%= link_to "New experience", new_experience_path %>

app/views/experiences/new.html.erb
<h1>New experience</h1>

<%= render "form", experience: @experience %>

<br>

<div>
  <%= link_to "Back to experiences", experiences_path %>
</div>

app/views/experiences/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @experience %>

<div>
  <%= link_to "Edit this experience", edit_experience_path(@experience) %> |
  <%= link_to "Back to experiences", experiences_path %>

  <%= button_to "Destroy this experience", @experience, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>Cadastro de Curriculos</h1>
<p>Encontre o Perfil ideial para o seu Negócio.</p>

<%= form_with url: search_path, method: :get do %>
  <%= label_tag :q, 'Busca:' %>
  <%= text_field_tag :q %>
  <%= submit_tag 'Pesquisar' %>
<% end %>
<br>
<%= link_to "Novo Cadastro", new_profile_path %>
<br>
<ul>
  <% @profiles.each do |profile| %>
    <li><%= profile.name %><br>
    <%= profile.email %><br>
    <%= link_to "Ver profile", profile %></li>
    <br>
  <% end %>
</ul>

app/views/home/search.html.erb
<h1>Resultados da busca</h1>
<ul>
  <% @profiles.each do |profile| %>
      <li>
        <%= profile.name %><br>
        <%= profile.email %><br>
        <%= profile.phone %> <br>
        <%= link_to "Ver profile", profile %>
        <br>
      </li>
  <% end %>

  <%= link_to "Voltar para os Currículos", home_index_path %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cadastro de Curriculo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/profiles/_experience_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label "Nome da Empresa", style: "display: block" %>
    <%= f.text_field :name %>
  </div>
 
  <div class="field">
    <%= f.label "Data de Inicio", style: "display: block" %>
    <%= f.date_field :date_start %>
  </div>
 
  <div class="field">
    <%= f.label "Data Final", style: "display: block" %>
    <%= f.date_field :date_final %>
  </div>
  <div class="field">
    <%= f.label "Descrição", style: "display: block" %>
    <%= f.text_area :description, size: "70x5" %>
  </div>
  <br>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, method: :post do |form| %>
  <% if profile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label "Nome", style: "display: block" %>
    <%= form.search_field :name %>
  </div>

  <div>
    <%= form.label "E-mail", style: "display: block" %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label "Url", style: "display: block" %>
    <%= form.url_field :url %>
  </div>

  <div>
    <%= form.label "Telefone", style: "display: block" %>
    <%= form.telephone_field :phone %>
  </div>

  <h4>Experiência</h4>
  <div id="experiences">
    <%= form.fields_for :experiences do |experience| %>
      <%= render 'experience_fields', f: experience %>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<div id="<%= dom_id profile %>">
  <p>
    <strong>Nome:</strong>
    <%= profile.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= profile.email%>
  </p>

  <p>
    <strong>Url:</strong>
    <%= profile.url %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= profile.phone %>
  </p>

  <br>
  <h4>Experiência</h4>
  <br>
  <% profile.experiences.each do |experience|%>
    <p>
      <strong>Nome da Empresa:</strong>
      <%= experience.name %> 
    </p>
    <p>
      <strong>Data de Inicio:</strong>
      <%= post_date experience.date_start %>
    </p>
    <p>
      <strong>Data de Saída:</strong>
      <%= post_date experience.date_final %>
    </p>
    <p>
      <strong>Descrição:</strong>
      <%= experience.description %>
    </p>
  <%end%>
</div>

app/views/profiles/edit.html.erb
<h1>Editar Currículo</h1>

<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Mostrar Currículo", @profile %> |
<%= link_to "Voltar para os Currículos", home_index_path %>
</div>

app/views/profiles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Currículos</h1>

<div id="profiles">
  <% @profiles.each do |profile| %>
    <%= render profile %>
    <p>
      <%= link_to "Ver profile", profile %>
    </p>
  <% end %>
</div>

<%= link_to "Novo Cadastro", new_profile_path %><br>
<%= link_to "Voltar para os Currículos", home_index_path %>

app/views/profiles/new.html.erb
<h1>Novo Cadastro</h1>

<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Voltar aos cadastros", home_index_path %>
</div>

app/views/profiles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @profile %>

<div>
  <%= link_to "Editar Currículo", edit_profile_path(@profile) %> |
  <%= link_to "Voltar para os Currículos", home_index_path %>

  <%= button_to "Excluir o Currículo", @profile, method: :delete %>
</div>